# /opt/test_wordpress/docker-compose.yml
#                     .env
#                     nginx-conf.d/
#                     db-data/
#                     www-data/

version: '2.25'

networks:
    my_wordpress_network:
        driver: bridge

volumes:
    db-data:
    www-data:

services:

    database:
        image:          'mariadb:latest'
        container_name: 'mariadb'
        restart:        'always'
        env_file:       .env
        volumes:
            - './db-data:/var/lib/mysql'
        command: '--default-authentication-plugin=mysql_native_password'
        networks:
            - 'my_wordpress_network'

    wordpress:
        image:          'wordpress:6.5.0-php8.2-fpm'
        container_name: 'wordpress'
        restart:        'always'
        depends_on:
            - database
        env_file:        .env 
        environment:
            DB_HOST:     'database'
            DB_USER:     '$MARIADB_USER'
            DB_PASSWORD: '$MARIADB_PASSWORD'
            DB_NAME:     '$MARIADB_DATABASE'
        volumes:
            - './www-data:/var/www/html'
        networks:
            - 'my_wordpress_network'

    nginx:
        image:          'nginx:latest'
        container_name: 'nginx'
        restart:        'always'
        depends_on:
            - wordpress
        volumes:
            - './nginx-conf.d:/etc/nginx/conf.d'
            - './www-data:/var/www/html'
        networks:
            - 'my_wordpress_network'
        ports:
            - '80:80'

